sql:
  host: 127.0.0.1
  port: 3306
  database: minecraft
  username: sample
  password: sample
  table: ServerInfo
  datasize: 20

alert:
  ramUsageHigh: 4096
  cpuUsageHigh: 80

interval:
  unitInTick: 20
  alert: 1
  default: 5

