name: ServerInfo
version: 2.0-RELEASE-beta
main: com.kms1212.mcplugin.serverinfo.ServerInfo
api-version: 1.16
load: STARTUP
authors: [ kms1212 ]
description: Sends server information(CPU usage, RAM usage, Errors, Exceptions, etc.) to MySQL Server
commands:
  serverinfo:
    description: ServerInfo command.
    usage: "Commands : /<command> help"
    permission: <plugin name>.configure
    permission-message: You don't have permission to perform this command.
  si:
    description: ServerInfo command.
    usage: "Commands : /<command> help"
    permission: <plugin name>.configure
    permission-message: You don't have permission to perform this command.